# For all PRs, this workflow will
#     - Install deps
#     - Test
name: Linting files 
on:
  push:
    paths:
      - 'components/*'
jobs: 
 lint:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Prettify markdown
        uses: creyD/prettier_action@v3.0
        with:
            prettier_options: --write components/*
