name: Welcome
on:
  pull_request:
    types: [opened, closed]
  issues:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/welcome@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIRST_ISSUE: |
            👋 @{{ author }}
             Thanks for opening your first issue here! Be sure to follow the Status Code issue template if you creating an issue to add a newe Status Code.

          FIRST_PR: |
            👋 @{{ author }}
            Thanks for opening this pull request! Please ensure that this is related to an open issue and that your changes are not introducing a duplicate status code or image. 

          FIRST_PR_MERGED: |
            🎉 @{{ author }}
            Congrats on merging your first pull request! We over at httriri are proud of you!
